#!/usr/bin/env bash
# script to show information about a subdomain

domain=$1
subdomain=$2

info () {
	dig www.$domain | grep -A1 'ANSWER SECTION' |grep www.$domain | awk '{ print "The subdomain www is a " $4 " record and points to " $5}'
	dig lb-01.$domain | grep -A1 'ANSWER SECTION' |grep lb-01.$domain | awk '{ print "The subdomain lb-01 is a " $4 " record and points to " $5}'
	dig web-01.$domain | grep -A1 'ANSWER SECTION' |grep web-01.$domain | awk '{ print "The subdomain web-01 is a "$4 " record and points to " $5}'
	dig web-02.$domain | grep -A1 'ANSWER SECTION' |grep web-02.$domain | awk '{ print "The subdomain web-02 is a " $4 " record and points to " $5}'
}

if [ $# = 2 ]
then
	recordType=$(dig $subdomain.$domain | grep -A1 'ANSWER SECTION' |grep $subdomain.$domain | awk '{ print $4}')
	pointTo=$(dig $subdomain.$domain | grep -A1 'ANSWER SECTION' |grep $subdomain.$domain | awk '{ print $5}')
	echo "The subdomain $subdomain is a $recordType record and points to $pointTo"

elif [ $# = 1 ]
then
	info
fi

