#!/usr/bin/env bash
# script to show information about a subdomain
get_record_info() {
    local domain="$1"
    local subdomain="$2"
    local record_type="$3"
    local destination="$4"
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
else
    subdomains=("$subdomain")
fi

for sub in "${subdomains[@]}"; do
    record_type=$(dig +short -t AAAA "$sub.$domain" | awk '{print length($0) ? "AAAA" : "A"}')
    destination=$(dig +short "$sub.$domain")

    if [ -n "$destination" ]; then
        get_record_info "$domain" "$sub" "$record_type" "$destination"
    else
        echo "No information found for subdomain $sub.$domain"
    fi
done
