#!/usr/bin/env bash
# script to install nginx in a web server

sudo apt update -y
sudo apt install -y nginx
sudo chown -R "$USER":"$USER" /var/www
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
