#!/usr/bin/env bash
# script to install nginx in a web server and configure a redirect

sudo apt update
sudo apt install nginx -y
sudo chown -R "$USER":"$USER" /etc/nginx
sed -i "s#server_name _;#server_name 54.90.5.38/redirect_me;\n \treturn\t301 https://google.com;#1" /etc/nginx/sites-available/default
sudo systemctl restart nginx
