#!/usr/bin/env bash
# run nginx as user nginx
chmod 764 /etc/nginx/nginx.conf
sed -i "s#pid /run/nginx.pid;#pid /run/nginx.pid;\nuser nginx nginx;\n#1" /etc/nginx/nginx.conf
sudo -u nginx  service nginx restart
